#
# macros
#

[macros.mkdirp]
	prefix = ["mkdir", "-p"]

[macros.clone]
    prefix = ["git", "clone"]

[macros.go-get]
    prefix = ["go", "get"]

[macros.install__apt]
    prefix = ["sudo", "apt-get", "install", "-y"]

[macros.install__pacman]
    prefix = ["sudo", "pacman", "-S"]

[macros.install__brew]
    prefix = ["brew", "install"]


[macros.npm-install]
    deps = ["node"]
    prefix = ["npm", "install", "-g"]

#
# Tasks
#

[tasks.default]
	deps = ["bootstrap"]
    links = [
        [".editorconfig"],
		[".vimrc"],
		[".config/terminator/config", ".config/terminator/config"],
		[".config/neofetch/config", ".config/neofetch/config"]
    ]

[tasks.macos]
	deps = ["default"]
	links = [
		[".zshrc", ".zshrc.macos"],
	]

[tasks.server]
	deps = ["default"]
	links = [
		[".zshrc", ".zshrc.server"]
	]

[tasks.desktop]
	deps = ["default"]
	links = [
		[".zshrc", ".zshrc.desktop"],
	]

[tasks.bootstrap]
	cmds = [["touch", "${HM_DEST}/.zsh_secrets"], ["@mkdirp", "${HM_DEST}/go", "${HM_DEST}/.nmbin"], ["npm", "config", "set", "prefix", "${HM_DEST}/.nmbin"]]
