#
# macros
#

[macros.mkdirp]
	prefix = ["mkdir", "-p"]

[macros.clone]
    prefix = ["git", "clone"]

[macros.go-get]
    prefix = ["go", "get"]

[macros.install__apt]
    prefix = ["sudo", "apt-get", "install", "-y"]

[macros.install__pacman]
    prefix = ["sudo", "pacman", "-S"]

[macros.install__brew]
    prefix = ["brew", "install"]


[macros.npm-install]
    deps = ["node"]
    prefix = ["npm", "install", "-g"]

#
# Tasks
#

[tasks.default]
	deps = ["bootstrap"]
    links = [
        [".editorconfig"],
		[".vimrc"],
		[".tmux.conf"],
		[".config/terminator/"],
		[".config/neofetch/"],
		[".config/tilix/"],
		[".config/bspwm"],
		[".config/nvim"],
		[".config/i3"],
		[".config/fontconfig"],
		[".config/compton.conf"],
		[".config/alacritty"],
		[".config/rofi"],
		[".config/sxhkd"],
		[".config/polybar"],
		[".config/dunst"],
		["tilix_layout.json"],
		["Pictures/parrot-abstract.jpg"],
		[".bin/"],
    ]

[tasks.macos]
	deps = ["default"]
	links = [
		[".zshrc", ".zshrc.macos"],
	]
[tasks.archmbp]
	deps = ["default"]
	links = [
		[".zshrc", ".zshrc.archmbp"],
	]

[tasks.server]
	deps = ["default"]
	links = [
		[".zshrc", ".zshrc.server"]
	]

[tasks.desktop]
	deps = ["default"]
	links = [
		[".zshrc", ".zshrc.desktop"],
	]

[tasks.bootstrap]
	cmds = [["touch", "${HM_DEST}/.zsh_secrets"], ["@mkdirp", "${HM_DEST}/go", "${HM_DEST}/.nmbin"], ["npm", "config", "set", "prefix", "${HM_DEST}/.nmbin"]]
