 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Android File Transfer (MTP)", "android-file-transfer", "/usr/share/icons/hicolor/128x128/apps/android-file-transfer.png" },
     {"Archive Manager", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"Caffeine-ng", "/usr/bin/caffeine", "/usr/share/icons/hicolor/16x16/apps/caffeine.png" },
     {"Calculator", "gnome-calculator"},
     {"Disks", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
     {"Etcher", "\"/opt/Etcher/etcher-electron\" ", "/usr/share/icons/hicolor/16x16/apps/etcher-electron.png" },
     {"FeatherPad", "featherpad "},
     {"Files", "nautilus --new-window ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Nautilus.png" },
     {"Firejail Configuration Wizard", "firejail-ui", "/usr/share/pixmaps/firejail-ui.png" },
     {"Fonts", "gnome-font-viewer "},
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"KeePass Password Safe", "keepass", "/usr/share/icons/hicolor/16x16/apps/keepass.png" },
     {"Maps", "gapplication launch org.gnome.Maps", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Maps.png" },
     {"Neovim", "xterm -e nvim ", "/usr/share/pixmaps/nvim.png" },
     {"Passwords and Keys", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"PlayOnLinux", "playonlinux"},
     {"Postman", "postman ", "/usr/share/icons/hicolor/128x128/apps/postman.png" },
     {"Redshift", "redshift-gtk"},
     {"Screenshot", "gnome-screenshot --interactive"},
     {"Text Editor", "gedit ", "/usr/share/icons/hicolor/16x16/apps/gedit.png" },
     {"Visual Studio Code", "/opt/visual-studio-code/code ", "/usr/share/icons/visual-studio-code.png" },
     {"Weather", "gapplication launch org.gnome.Weather.Application", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Weather.png" },
     {"WebCatalog", "\"/opt/WebCatalog/webcatalog\" ", "/usr/share/icons/hicolor/16x16/apps/webcatalog.png" },
     {"compton", "compton --xrender-sync-fence", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Image Viewer", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"Peek", "peek", "/usr/share/icons/hicolor/16x16/apps/com.uploadedlobster.peek.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh"},
     {"Avahi VNC Server Browser", "/usr/bin/bvnc"},
     {"Caprine", "caprine"},
     {"Chromium", "/usr/bin/chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Discord", "/usr/bin/discord", "///usr/share/pixmaps/discord.png" },
     {"ELinks", "xterm -e /usr/bin/elinks "},
     {"Firefox Developer Edition", "/usr/lib/firefox-developer-edition/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox-developer-edition.png" },
     {"Geary", "geary ", "/usr/share/icons/hicolor/16x16/apps/geary.png" },
     {"KDE Connect Indicator", "kdeconnect-indicator", "/usr/share/icons/hicolor/16x16/apps/kdeconnect.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"Polari", "gapplication launch org.gnome.Polari", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Polari.png" },
     {"Remote Desktop Viewer", "vinagre "},
     {"ScudCloud", "scudcloud", "///usr/share/pixmaps/scudcloud.png" },
     {"Slack", "env LD_PRELOAD=/usr/lib/libcurl.so.3 /usr/bin/slack --disable-gpu ", "/usr/share/pixmaps/slack.png" },
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Syncthing GTK", "syncthing-gtk", "/usr/share/icons/hicolor/16x16/apps/syncthing-gtk.png" },
     {"TeamViewer 13", "/opt/teamviewer/tv_bin/script/teamviewer", "/usr/share/icons/hicolor/16x16/apps/TeamViewer.png" },
     {"Telegram Desktop", "telegram-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/telegram.png" },
     {"Tor-Browser (en-US)", "/usr/bin/tor-browser-en", "/usr/share/pixmaps/tor-browser-en.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"Wireshark (GTK+)", "wireshark-gtk ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"X11VNC Server", "x11vnc -gui tray=setpass -rfbport PROMPT -bg -o %HOME/.x11vnc.log.%VNCDISPLAY"},
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calendar", "gnome-calendar", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Calendar.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"Evolution", "evolution ", "/usr/share/icons/hicolor/16x16/apps/evolution.png" },
     {"Texmaker", "texmaker ", "/usr/share/pixmaps/texmaker.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"GitKraken", "gitkraken", "/usr/share/pixmaps/gitkraken.png" },
     {"JetBrains Toolbox", "/usr/bin/jetbrains-toolbox", "///usr/share/pixmaps/jetbrains-toolbox.svg" },
     {"Postman", "postman ", "/usr/share/icons/hicolor/128x128/apps/postman.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Visual Studio Code", "/opt/visual-studio-code/code ", "/usr/share/icons/visual-studio-code.png" },
     {"Zeal", "zeal ", "/usr/share/icons/hicolor/16x16/apps/zeal.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Brasero", "brasero ", "/usr/share/icons/hicolor/16x16/apps/brasero.png" },
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Cheese.png" },
     {"Clementine", "clementine ", "/usr/share/icons/hicolor/64x64/apps/clementine.png" },
     {"Gnome Music Player Client", "gmpc", "/usr/share/icons/hicolor/16x16/apps/gmpc.png" },
     {"Mopidy", "xterm -e mopidy"},
     {"Music", "gnome-music", "/usr/share/icons/hicolor/16x16/apps/gnome-music.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Sound Recorder", "gnome-sound-recorder", "/usr/share/icons/hicolor/16x16/apps/gnome-sound-recorder.png" },
     {"Streamlink Twitch GUI", "/usr/bin/streamlink-twitch-gui", "/usr/share/icons/hicolor/16x16/apps/streamlink-twitch-gui.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Videos", "totem ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Totem.png" },
     {"avidemux (Qt)", "avidemux3_qt5", "/usr/share/pixmaps/avidemux.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Alacritty", "alacritty"},
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Color Profile Viewer", "gcm-viewer", "/usr/share/icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Configuration Editor", "gconf-editor", "/usr/share/icons/hicolor/16x16/apps/gconf-editor.png" },
     {"Disk Usage Analyzer", "baobab", "/usr/share/icons/hicolor/16x16/apps/baobab.png" },
     {"Firetools", "firetools", "/usr/share/pixmaps/firetools.png" },
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Libinput Gestures", "/usr/bin/libinput-gestures", "/usr/share/icons/hicolor/128x128/apps/libinput-gestures.png" },
     {"Logs", "gnome-logs", "/usr/share/icons/hicolor/16x16/apps/gnome-logs.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"Sakura", "sakura", "/usr/share/pixmaps/terminal-tango.svg" },
     {"System Monitor", "gnome-system-monitor"},
     {"Terminal", "gnome-terminal"},
     {"Tilix", "tilix", "/usr/share/icons/hicolor/16x16/apps/com.gexperts.Tilix.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"VeraCrypt", "veracrypt", "/usr/share/pixmaps/veracrypt.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"ranger", "xterm -e ranger"},
     {"urxvt", "urxvt"},
     {"urxvt (client)", "urxvtc"},
     {"urxvt (tabbed)", "urxvt-tabbed"},
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

